### ISSUE TITLE
Typo in type import `SharedImigixAndSourceProps`

### ISSUE THREAD

**Issue by klaasman** [delicious-simplicity/next-image-imgix-loader#2]
See latest release on npm, content of the type declarations: https://www.unpkg.com/browse/@delicious-simplicity/next-image-imgix-loader@1.1.0/types/nextImgixLoader.d.ts

```tsx
import { SharedImigixAndSourceProps } from 'react-imgix';
                 ^

// which should become:
import { SharedImgixAndSourceProps } from 'react-imgix';
```

It looks like it has already been resolved in your latest pnpm commit - so a new release should do the trick. :-)

**Comment by devjmetivier** [comment]
Thanks for the callout! Released in [v1.1.1](https://github.com/delicious-simplicity/next-image-imgix-loader/releases/tag/%40delicious-simplicity%2Fnext-image-imgix-loader%40v1.1.1)
